---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sysdig-gcscc-connector
data:
  org_id: "534901558763"
  project_id: cscc544401558763
  source_id: "534932342125324852345265233"
  webhook_url: https://arboreal-logic-198306.appspot.com/events
---
kind: Secret
apiVersion: v1
metadata:
  name: sysdig-gcscc-connector
type: Opaque
data:
  sysdig_token: YzZmNmFmODYtOTNhNS00MThiLTlkNzYtMTIyOWZjZDkyMzc4Cg==
  webhook_authentication_token: N2E3OTQxNmVkNGQzNzc2Yjc0ZmNjMDcwMjc1ZWNlMjA4ZWVlZjI5Zgo=
  security_service_account_info: J3sidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLCAicHJvamVjdF9pZCI6ICIiLCAicHJpdmF0ZV9rZXlfaWQiOiAiIiwgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsICJjbGllbnRfZW1haWwiOiAiIiwgImNsaWVudF9pZCI6ICIiLCAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCAidG9rZW5fdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi90b2tlbiIsICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwgImNsaWVudF94NTA5X2NlcnRfdXJsIjogIiJ9Jwo=
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sysdig-gcscc-connector
  labels:
    name: sysdig-gcscc-connector-deployment
    app: sysdig-gcscc-connector-app
spec:
  replicas: 2
  selector:
    matchLabels:
     name: sysdig-gcscc-connector
     role: sysdig-gcscc-connector
     app: sysdig-gcscc-connector-app
  template:
    spec:
      containers:
        - name: sysdig-gcscc-connector
          image: sysdig/sysdig-gcscc-connector
          # You can deploy instead the sysdig_secure_webhook
          args: [ "falco_webhook" ]
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SYSDIG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sysdig-gcscc-connector
                  key: sysdig_token
            - name: ORG_ID
              valueFrom:
                configMapKeyRef:
                  name: sysdig-gcscc-connector
                  key: org_id
            - name: SOURCE_ID
              valueFrom:
                configMapKeyRef:
                  name: sysdig-gcscc-connector
                  key: source_id
            - name: SECURITY_SERVICE_ACCOUNT_INFO
              valueFrom:
                secretKeyRef:
                  name: sysdig-gcscc-connector
                  key: security_service_account_info
            - name: WEBHOOK_AUTHENTICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sysdig-gcscc-connector
                  key: webhook_authentication_token
    metadata:
      labels:
        name: sysdig-gcscc-connector
        role: sysdig-gcscc-connector
        app: sysdig-gcscc-connector-app
---
apiVersion: v1
kind: Service
metadata:
  name: sysdig-gcscc-connector
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: sysdig-gcscc-connector
    app: sysdig-gcscc-connector-app
    role: sysdig-gcscc-connector
